version: '3'

services:
  db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD
  web:
    build: .
    environment:
     - POSTGRES_PASSWORD
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django_web_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
     - db